### ISSUE TITLE
Wasn't able to get the docker image running (Illegal instruction (core dumped)) (no AVX support?)

### ISSUE THREAD

**Issue by voarsh2** [ravenscroftj/turbopilot#6]
```
main: seed = 1681324505

Illegal instruction (core dumped)

```

Wasn't able to get the docker image running.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.100.103"],"port":32435,"protocol":"TCP","serviceName":"serge:turbopilot-nodeport","allNodes":true}]'
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-serge-turbopilot
  name: turbopilot
  namespace: serge
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-serge-turbopilot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-serge-turbopilot
    spec:
      containers:
      - env:
        - name: MODEL
          value: /models/codegen-2B-multi-ggml-4bit-quant.bin
        image: ghcr.io/ravenscroftj/turbopilot/turbopilot:latest
        imagePullPolicy: IfNotPresent
        name: container-0
        ports:
        - containerPort: 18080
          name: turbopilot
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /models
          name: turbopilot
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: turbopilot
        persistentVolumeClaim:
          claimName: turbopilot

```
